apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: docker.io/bitnami/nginx:1.25.2-debian-11-r3
        name: nginx
        resources:
          requests:
            cpu: 1m
            memory: 1Mi
        ports:
        - containerPort: 2001
