apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: docker.io/bitnami/nginx:1.25.2-debian-11-r3
        name: guestbook-ui
        resources:
          requests:
            cpu: 1m
            memory: 1Mi
        ports:
        - containerPort: 80
